version: "3.9"

services:
  backend:
    build: ./backend
    image: ${BACKEND_IMAGE:-political-dashboard-backend}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: ${FRONTEND_IMAGE:-political-dashboard-frontend}
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
